on: 
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.19
      with:
        build_command: make build-release
        pre_command: set
        binary_name: clippan-release
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: amd64
