name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        go-version: [ 1.15.x, 1.16.x, 1.17.x, 1.18.x ]
        couchdb: [3.1]

    name: Go ${{ matrix.go-version }}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Start CouchDB
        uses: iamssen/couchdb-github-action@master
        with:
          couchdb-version: ${{ matrix.couchdb }}

      - name: Run the tests
        env:
          COUCHDB_TESTING_DATABASE: "http://admin:password@127.0.0.1:5984"
        run: go test -v ./...
